var very = "very";

// exports browsers
// new browsers should only be added once they have at least a single 'true' result.

module.exports = {
  es6tr: {
    full: 'ES6 Transpiler',
    short: 'ES6<br>Trans-<br>piler',
    obsolete: true,
    platformtype: 'compiler',
    test_suites: ['es6'],
  },
  tr: {
    full: 'Traceur',
    short: 'Traceur',
    platformtype: 'compiler',
    obsolete: false,
    test_suites: ['es6', 'es2016plus', 'esnext'],
  },
  babel: {
    full: 'Babel 6.5 + core-js 2.4',
    short: 'Babel +<br><nobr>core-js</nobr>',
    platformtype: 'compiler',
    note_id: 'babel-optional',
    note_html: 'Flagged features require an optional transformer setting.',
    obsolete: false,
    test_suites: ['es6', 'es2016plus', 'esnext'],
  },
  closure: {
    full: 'Closure Compiler v20161024',
    short: 'Closure',
    platformtype: 'compiler',
    obsolete: false,
    test_suites: ['es6', 'es2016plus', 'esnext'],
  },
  jsx: {
    full: 'JSX',
    short: 'JSX',
    platformtype: 'compiler',
    obsolete: true,
    test_suites: ['es6'],
  },
  typescript: {
    full: 'TypeScript 1.8 + core-js 2.4',
    short: 'Type-<br />Script +<br /><nobr>core-js</nobr>',
    platformtype: 'compiler',
    obsolete: false,
    test_suites: ['es6', 'es2016plus', 'esnext'],
  },
  es5shim: {
    full: 'es5-shim',
    short: 'es5-shim',
    obsolete: false,
    platformtype: 'compiler',
    test_suites: ['es5'],
  },
  es6shim: {
    full: 'es6-shim',
    short: 'es6-shim',
    platformtype: 'compiler',
    obsolete: false,
    test_suites: ['es6'],
  },
  es7shim: {
    full: 'es7-shim',
    short: 'es7-shim',
    platformtype: 'compiler',
    obsolete: false,
    test_suites: ['es2016plus'],
  },
  konq43: {
    full: 'Konqueror 4.3',
    family: 'KJS',
    short: 'Konq 4.3',
    obsolete: true,
    test_suites: ['es5'],
  },
  konq44: {
    full: 'Konqueror 4.4',
    short: 'Konq 4.4',
    family: 'KJS',
    obsolete: true,
    test_suites: ['es5', 'non-standard'],
  },
  konq49: {
    full: 'Konqueror 4.9',
    family: 'KJS',
    short: 'Konq 4.9',
    obsolete: true,
    test_suites: ['es5', 'non-standard'],
  },
  konq413: {
    full: 'Konqueror 4.13',
    family: 'KJS',
    short: 'Konq 4.13',
    obsolete: true,
    test_suites: ['es5'],
  },
  konq414: {
    full: 'Konqueror 4.14',
    short: 'KQ<br>4.14',
    family: 'KJS',
    note_id: 'khtml',
    note_html: 'Results are only applicable for the KHTML rendering engine.',
    test_suites: ['es5', 'es6'],
  },
  ie7: {
    full: 'Internet Explorer 7',
    family: 'Chakra',
    short: 'IE 7',
    obsolete: true,
    test_suites: ['es5', 'es6', 'esnext', 'non-standard'],
  },
  ie8: {
    full: 'Internet Explorer 8',
    family: 'Chakra',
    short: 'IE 8',
    obsolete: true,
    test_suites: ['es5', 'es6', 'esnext', 'non-standard'],
  },
  ie9: {
    full: 'Internet Explorer 9',
    family: 'Chakra',
    short: 'IE 9',
    obsolete: true
  },
  ie10: {
    full: 'Internet Explorer',
    family: 'Chakra',
    short: 'IE 10',
    obsolete: true,
  },
  ie11: {
    full: 'Internet Explorer',
    family: 'Chakra',
    short: 'IE 11',
    obsolete: false // no EOL any time soon
  },
  edge12: {
    full: 'Microsoft Edge',
    family: 'Chakra',
    short: 'Edge 12',
    note_id: 'edge-experimental-flag',
    note_html: 'Flagged features have to be enabled via "Enable experimental Javascript features" setting under about:flags',
    obsolete: true,
  },
  edge13: {
    full: 'Microsoft Edge',
    family: 'Chakra',
    short: 'Edge 13',
    note_id: 'edge-experimental-flag',
    note_html: 'Flagged features have to be enabled via "Enable experimental Javascript features" setting under about:flags'
  },
  edge14: {
    full: 'Microsoft Edge',
    family: 'Chakra',
    short: 'Edge 14',
    note_id: 'edge-experimental-flag',
    note_html: 'Flagged features have to be enabled via "Enable experimental Javascript features" setting under about:flags'
  },
  firefox2: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 2',
    obsolete: very,
  },
  firefox3: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 3',
    obsolete: very,
  },
  firefox3_5: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 3.5',
    obsolete: very,
  },
  firefox3_6: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 3.6',
    obsolete: very,
  },
  firefox4: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 4',
    obsolete: very,
  },
  firefox5: {
    full: 'Firefox 5',
    family: 'SpiderMonkey',
    short: 'FF 5',
    obsolete: very
  },
  firefox6:{
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 6',
    obsolete: very,
  },
  firefox7: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 7',
    obsolete: very,
  },
  firefox8: {
    full: 'Firefox 8',
    family: 'SpiderMonkey',
    short: 'FF 8',
    obsolete: very,
  },
  firefox10: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 10<br> ESR',
    obsolete: very, // ESR (EOL on February 12, 2013)
  },
  firefox12: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 12',
    obsolete: very,
  },
  firefox13: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 13',
    obsolete: very,
  },
  firefox15: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 15',
    obsolete: very,
  },
  firefox16: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 16',
    obsolete: very,
  },
  firefox17: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 17<br> ESR',
    obsolete: very, // ESR (EOL on December 3, 2013)
  },
  firefox18: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 18',
    obsolete: very,
  },
  firefox19: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 19',
    obsolete: very,
  },
  firefox20: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 20',
    obsolete: very,
  },
  firefox21: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 21',
    obsolete: very,
  },
  firefox22: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 22',
    obsolete: very,
  },
  firefox23: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 23',
    obsolete: very,
  },
  firefox24: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 24<br> ESR',
    obsolete: very, // ESR (EOL on October 14, 2014)
  },
  firefox25: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 25',
    obsolete: very,
  },
  firefox26: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 26',
    obsolete: very,
  },
  firefox27: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 27',
    obsolete: very,
  },
  firefox28: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 28',
    obsolete: very,
  },
  firefox29: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 29',
    obsolete: very,
  },
  firefox30: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 30',
    obsolete: very,
  },
  firefox31: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 31<br> ESR',
    obsolete: true, // ESR (EOL on August 11, 2015)
  },
  firefox32: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 32',
    obsolete: very,
  },
  firefox33: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 33',
    obsolete: very,
  },
  firefox34: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 34',
    obsolete: very,
  },
  firefox35: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 35',
    obsolete: very,
  },
  firefox36: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 36',
    obsolete: very,
  },
  firefox37: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 37',
    obsolete: very,
  },
  firefox38: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 38<br> ESR',
    obsolete: true, // ESR (EOL on June 7, 2016)
  },
  firefox39: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 39',
    obsolete: very,
  },
  firefox40: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 40',
    obsolete: true,
  },
  firefox41: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 41',
    obsolete: true,
  },
  firefox42: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 42',
    obsolete: true,
  },
  firefox43: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 43',
    obsolete: true,
  },
  firefox44: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 44',
    obsolete: true,
  },
  firefox45: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 45 ESR',
    obsolete: false, // ESR (EOL at Mar 2017)
  },
  firefox46: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 46',
    obsolete: true,
  },
  firefox47: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 47',
    obsolete: true,
  },
  firefox48: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 48',
    obsolete: true,
  },
  firefox49: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 49',
    obsolete: true,
  },
  firefox50: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 50',
  },
  firefox51: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 51 Beta',
    unstable: true,
  },
  firefox52: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 52 Aurora',
    unstable: true,
  },
  firefox53: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 53 Nightly',
    unstable: true,
  },
  opera10_10: {
    full: 'Opera 10.10',
    family: 'Carakan',
    short: 'OP 10.1',
    obsolete: true,
    test_suites: ['es5'],
  },
  opera10_50: {
    full: 'Opera 10.50, Opera 10.62 (build 8437), Opera 10.70 (build 9044), Opera 11 (build 1156), Opera 11.10 (build 2048), Opera 11.11 (build 2109), Opera 11.50 (build 1074)',
    family: 'Carakan',
    short: 'OP 10.50-11.50',
    obsolete: true,
    test_suites: ['es5'],
  },
  opera12: {
    full: 'Opera 12',
    family: 'Carakan',
    short: 'OP 12',
    obsolete: true,
    test_suites: ['es5', 'es6'],
  },
  opera12_10: {
    full: 'Opera 12.15',
    family: 'Carakan',
    short: 'OP 12.10',
    obsolete: true,
    test_suites: ['es5', 'es6', 'esintl'],
  },
  chrome5: {
    full: 'Chrome 5 (5.0.375.127)',
    family: 'V8',
    short: 'CH 5',
    note_id: 'experimental-flag',
    obsolete: very,
  },
  chrome6: {
    full: 'Chrome 6 (6.0.472.55)',
    family: 'V8',
    short: 'CH 6',
    note_id: 'experimental-flag',
    obsolete: very,
  },
  chrome7: {
    full: 'Chrome 7 (7.0.517.5), Chrome 8, Chrome 9 (9.0.587.0 dev), Chrome 10, Chrome 11, Chrome 12 (12.0.742.91)',
    family: 'V8',
    short: 'CH 7-12',
    note_id: 'experimental-flag',
    obsolete: very,
  },
  chrome11: {
    full: 'Chrome 11',
    family: 'V8',
    short: 'CH 11',
    note_id: 'experimental-flag',
    obsolete: very,
  },
  chrome13: {
    full: 'Chrome 13 (13.0.782.107 beta), Chrome 14 (14.0.835.8 dev), Chrome 15, Chrome 16 (16.0.891.0 dev)',
    family: 'V8',
    short: 'CH 13-16',
    note_id: 'experimental-flag',
    obsolete: very,
  },
  chrome19: {
    full: 'Chrome',
    family: 'V8',
    short: 'CH 19',
    obsolete: very,
    note_id: 'experimental-flag',
    note_html: 'Flagged features have to be enabled via "Experimental Javascript features" flag'
  },
  chrome21: {
    full: 'Chrome',
    family: 'V8',
    short: 'CH 21',
    obsolete: very,
    note_id: 'experimental-flag',
  },
  chrome22: {
    full: 'Chrome',
    family: 'V8',
    short: 'CH 22',
    obsolete: very,
    note_id: 'experimental-flag',
  },
  chrome23: {
    full: 'Chrome 23-24, Opera 15',
    family: 'V8',
    short: 'CH 23-24,<br>OP 15',
    obsolete: very,
    note_id: 'experimental-flag',
  },
  chrome24: {
    full: 'Chrome 24-28, Opera 15',
    family: 'V8',
    short: 'CH 24-29,<br>OP 15',
    obsolete: very,
    note_id: 'experimental-flag',
  },
  chrome29: {
    full: 'Chrome 29, Opera 16',
    family: 'V8',
    short: 'CH 29,<br>OP 16',
    obsolete: very,
    note_id: 'experimental-flag',
  },
  chrome30: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH&nbsp;30,<br>OP&nbsp;17',
    obsolete: very,
    note_id: 'experimental-flag',
  },
  chrome31: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH&nbsp;31,<br>OP&nbsp;18',
    obsolete: very,
    note_id: 'experimental-flag',
  },
  chrome33: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH&nbsp;32-33,<br>OP&nbsp;19-20',
    obsolete: very,
    note_id: 'experimental-flag',
  },
  chrome34: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH&nbsp;34,<br>OP&nbsp;21',
    obsolete: very,
    note_id: 'experimental-flag',
  },
  chrome35: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH&nbsp;35,<br>OP&nbsp;22',
    obsolete: very,
    note_id: 'experimental-flag',
  },
  chrome36: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH&nbsp;36,<br>OP&nbsp;23',
    obsolete: very,
    note_id: 'experimental-flag',
  },
  chrome37: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH&nbsp;37,<br>OP&nbsp;24',
    obsolete: very,
    note_id: 'experimental-flag',
  },
  chrome38: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH&nbsp;38,<br>OP&nbsp;25',
    obsolete: very,
    note_id: 'experimental-flag',
  },
  chrome39: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH 39,<br>OP&nbsp;26',
    obsolete: very,
    note_id: 'experimental-flag',
  },
  chrome40: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH 40,<br>OP&nbsp;27',
    obsolete: very,
    note_id: 'experimental-flag',
  },
  chrome41: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH 41,<br>OP&nbsp;28',
    obsolete: very,
    note_id: 'experimental-flag',
  },
  chrome42: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH 42,<br>OP&nbsp;29',
    obsolete: very,
    note_id: 'experimental-flag',
  },
  chrome43: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH 43,<br>OP&nbsp;30',
    obsolete: very,
    note_id: 'experimental-flag',
  },
  chrome44: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH 44,<br>OP&nbsp;31',
    obsolete: very,
    note_id: 'experimental-flag',
  },
  chrome45: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH 45,<br>OP&nbsp;32',
    obsolete: true,
    note_id: 'experimental-flag',
  },
  chrome46: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH 46,<br>OP&nbsp;33',
    obsolete: true,
    note_id: 'experimental-flag',
  },
  chrome47: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH 47,<br>OP&nbsp;34',
    obsolete: true,
    note_id: 'experimental-flag',
  },
  chrome48: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH 48,<br>OP&nbsp;35',
    obsolete: true,
    note_id: 'experimental-flag',
  },
  chrome49: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH 49,<br>OP&nbsp;36',
    obsolete: true,
    note_id: 'experimental-flag',
  },
  chrome50: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH 50,<br>OP&nbsp;37',
    obsolete: true,
    note_id: 'experimental-flag',
  },
  chrome51: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH 51,<br>OP&nbsp;38',
    obsolete: true,
    note_id: 'experimental-flag',
  },
  chrome52: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH&nbsp;52,<br>OP&nbsp;39',
    obsolete: true,
    note_id: 'experimental-flag',
  },
  chrome53: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH&nbsp;53,<br>OP&nbsp;40',
    note_id: 'experimental-flag',
    obsolete: true,
  },
  chrome54: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH&nbsp;54,<br>OP&nbsp;41',
    note_id: 'experimental-flag',
    obsolete: false,
  },
  chrome55: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH&nbsp;55,<br>OP&nbsp;42',
    note_id: 'experimental-flag',
    unstable: true,
  },
  chrome56: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH&nbsp;56,<br>OP&nbsp;43',
    note_id: 'experimental-flag',
    unstable: true,
  },
  chrome57: {
    full: 'Chrome, Opera',
    family: 'V8',
    short: 'CH&nbsp;57,<br>OP&nbsp;44',
    note_id: 'experimental-flag',
    unstable: true,
  },
  safari3: {
    full: 'Safari 3.2',
    family: 'JavaScriptCore',
    short: 'SF 3.2',
    obsolete: very,
  },
  safari4: {
    full: 'Safari 4.0.5',
    family: 'JavaScriptCore',
    short: 'SF 4',
    obsolete: very,
  },
  safari5: {
    full: 'Safari 5.0.5',
    family: 'JavaScriptCore',
    short: 'SF 5',
    obsolete: true,
    test_suites: ['es5', 'es6', 'esnext', 'non-standard'],
  },
  safari51: {
    full: 'Safari',
    family: 'JavaScriptCore',
    short: 'SF<br />5.1',
    obsolete: true,
  },
  safari6: {
    full: 'Safari',
    family: 'JavaScriptCore',
    short: 'SF 6',
    obsolete: true
  },
  safari7: {
    full: 'Safari',
    family: 'JavaScriptCore',
    short: 'SF 6.1,<br>SF 7',
    obsolete: true
  },
  safari71_8: {
    full: 'Safari',
    family: 'JavaScriptCore',
    short: 'SF 7.1,<br>SF 8',
    obsolete: true
  },
  safari9: {
    full: 'Safari',
    family: 'JavaScriptCore',
    short: 'SF 9',
    obsolete: false,
  },
  safari10: {
    full: 'Safari',
    family: 'JavaScriptCore',
    short: 'SF 10',
    obsolete: false,
  },
  safaritp: {
    full: 'Safari Technology Preview Release 18',
    family: 'JavaScriptCore',
    short: 'SF TP',
    unstable: true,
  },
  webkit: {
    full: 'Webkit r208586 (November 11, 2016)',
    family: 'JavaScriptCore',
    short: 'WK',
    unstable: true,
  },
  rhino17: {
    full: 'Rhino 1.7',
    short: 'Rhino 1.7',
    platformtype: 'engine',
    obsolete: true,
    test_suites: ['es5', 'es6', 'non-standard'],
  },
  besen: {
    full: 'Bero\'s EcmaScript Engine (version 1.0.0.489)',
    short: 'BESEN',
    link: 'http://besen.sourceforge.net/',
    obsolete: false,
    platformtype: 'engine',
    test_suites: ['es5', 'non-standard'],
  },
  phantom: {
    full: 'PhantomJS 2.0',
    short: 'PJS',
    platformtype: 'engine',
    equals: 'safari6',
    // As PJS is a "headless browser" that emulates a real browser, it technically should support annex B.
    needs_annex_b: true,
  },
  ejs: {
    full: 'Echo JS',
    short: 'Echo JS',
    platformtype: 'engine',
    unstable: true,
    test_suites: ['es5', 'es6'],
  },
  xs6: {
    full: 'Kinoma XS6',
    short: 'XS6',
    platformtype: 'engine',
    test_suites: ['es6'],
  },
  jxa: {
    full: 'JavaScript Automation for OS X',
    short: 'JXA',
    platformtype: 'engine',
    test_suites: ['es6'],
  },
  node010: {
    full: 'Node.js',
    family: 'Node.js',
    short: 'Node 0.10',
    platformtype: 'engine',
    note_id: 'harmony-flag',
    note_html: 'Flagged features have to be enabled via <code>--harmony</code> or <code>--es_staging</code> flag',
    obsolete: true, // Long-term support ends October 31, 2016.
    test_suites: ['es6', 'es2016plus', 'esnext', 'esintl'],
  },
  node012: {
    full: 'Node.js',
    family: 'Node.js',
    short: 'Node 0.12',
    platformtype: 'engine',
    note_id: 'harmony-flag',
    note_html: 'Flagged features have to be enabled via <code>--harmony</code> or <code>--es_staging</code> flag',
    obsolete: false, // Long-term support ends December 31, 2016.
    test_suites: ['es6', 'es2016plus', 'esnext', 'esintl'],
  },
  iojs: {
    full: 'io.js',
    family: 'Node.js',
    short: 'io.js',
    platformtype: 'engine',
    note_id: 'harmony-flag',
    obsolete: true,
    test_suites: ['es6', 'es2016plus', 'esnext', 'esintl'],
  },
  node4: {
    full: 'Node.js',
    family: 'Node.js',
    short: 'Node 4',
    equals: 'chrome44',
    platformtype: 'engine',
    note_id: 'harmony-flag',
    obsolete: false, // Long-term support ends April 1, 2018.
    test_suites: ['es6', 'es2016plus', 'esnext', 'esintl'],
  },
  node5: {
    full: 'Node.js',
    family: 'Node.js',
    short: 'Node 5',
    platformtype: 'engine',
    note_id: 'harmony-flag',
    obsolete: true,
    test_suites: ['es6', 'es2016plus', 'esnext', 'esintl'],
  },
  node64: {
    full: 'Node.js',
    family: 'Node.js',
    short: 'Node 6.0-6.4',
    platformtype: 'engine',
    note_id: 'harmony-flag',
    equals: 'chrome50',
    obsolete: true,
    test_suites: ['es6', 'es2016plus', 'esnext', 'esintl'],
  },
  node65: {
    full: 'Node.js',
    family: 'Node.js',
    short: 'Node 6.5',
    platformtype: 'engine',
    note_id: 'harmony-flag',
    equals: 'chrome51',
    obsolete: false, // Long-term support ends April 18, 2019.
    test_suites: ['es6', 'es2016plus', 'esnext', 'esintl'],
  },
  node7: {
    full: 'Node.js',
    family: 'Node.js',
    short: 'Node 7',
    platformtype: 'engine',
    note_id: 'harmony-flag',
    equals: 'chrome54',
    obsolete: false,
    test_suites: ['es6', 'es2016plus', 'esnext', 'esintl'],
  },
  android40: {
    full: 'Android Browser',
    short: 'AN 4.0',
    platformtype: 'mobile',
    obsolete: true,
  },
  android41: {
    full: 'Android Browser',
    short: 'AN 4.1',
    platformtype: 'mobile',
    obsolete: true,
  },
  android42: {
    full: 'Android Browser',
    short: 'AN 4.2',
    platformtype: 'mobile',
    obsolete: true,
  },
  android43: {
    full: 'Android Browser',
    short: 'AN 4.3',
    platformtype: 'mobile',
    obsolete: true,
  },
  android44: {
    full: 'Android Browser',
    short: 'AN 4.4',
    platformtype: 'mobile',
    equals: 'chrome30',
    ignore_flagged: true,
  },
  android50: {
    full: 'Android Browser',
    short: 'AN 5.0',
    platformtype: 'mobile',
    equals: 'chrome37',
    ignore_flagged: true,
  },
  android51: {
    full: 'Android Browser',
    short: 'AN 5.1',
    platformtype: 'mobile',
    equals: 'chrome39',
    ignore_flagged: true,
  },
  ios51: {
    full: 'iOS Safari',
    family: 'iOS Safari',
    short: 'iOS 5.1',
    platformtype: 'mobile',
    obsolete: true,
  },
  ios6: {
    full: 'iOS Safari',
    family: 'iOS Safari',
    short: 'iOS 6',
    platformtype: 'mobile',
    equals: 'safari51',
    obsolete: true,
  },
  ios7: {
    full: 'iOS Safari',
    family: 'iOS Safari',
    short: 'iOS 7',
    platformtype: 'mobile',
    equals: 'safari7',
    obsolete: true,
  },
  ios8: {
    full: 'iOS Safari',
    family: 'iOS Safari',
    short: 'iOS 8',
    platformtype: 'mobile',
    equals: 'safari7',
    obsolete: true,
  },
  ios9: {
    full: 'iOS Safari',
    family: 'iOS Safari',
    short: 'iOS 9',
    platformtype: 'mobile',
    equals: 'safari9',
    obsolete: false,
  },
  ios10: {
    full: 'iOS Safari',
    family: 'iOS Safari',
    short: 'iOS 10',
    platformtype: 'mobile',
    equals: 'safari10',
    obsolete: false,
  },
};
